security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_TUTEUR, ROLE_USER]
        ROLE_TUTEUR: [ROLE_USER]
        ROLE_PARENT: [ROLE_USER]
        ROLE_ELEVE: [ROLE_USER]

    # Gestion des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Fournisseur d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Configuration des pare-feu
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            login_throttling:
                max_attempts: 5
                interval: 1 hour
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_dashboard
                enable_csrf: true
            logout:
                path: app_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 7 jours (en secondes)
                path: '/' # Path disponible pour le cookie
                name: REMEMBERME # Nom du cookie
                always_remember_me: false # Optionnel : Active si l'utilisateur ne coche pas "Se souvenir de moi"

    # Contrôle d'accès
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/tuteur, roles: ROLE_TUTEUR }
        - { path: ^/eleve, roles: ROLE_ELEVE }
        - { path: ^/parent, roles: ROLE_PARENT }
        - { path: ^/progress, roles: ROLE_PARENT }
        - { path: ^/tutor/availability, roles: ROLE_TUTEUR }




when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
